"""专利审查规则初始化服务 - 完整版（100+规则）"""
from sqlalchemy import select
from app.database.models import ExaminationRule


# 预置专利审查规则 - 完整版（40+规则）
DEFAULT_PATENT_RULES = [
    # ═══════════════════════════════════════════════════════════════════════
    # 一级规则 - 基础形式审查规则 (20条)
    # ═══════════════════════════════════════════════════════════════════════
    
    # 1.1 文档完整性检查
    {
        "rule_name": "文档完整性检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 100,
        "is_active": True,
        "description": "检查专利申请文件是否完整，包括权利要求书、说明书、摘要等必要部分",
        "legal_basis": "专利法第26条",
        "severity": "error",
        "check_pattern": "structural",
        "target_fields": {"claims": True, "description": True, "abstract": True},
        "error_message": "缺少{field}",
        "fix_suggestion": "请补充完整的专利申请文件，包括：权利要求书、说明书、摘要、附图（如适用）",
    },
    # 1.2 格式规范性验证
    {
        "rule_name": "格式规范性验证",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 95,
        "is_active": True,
        "description": "验证文档格式是否符合专利局要求，包括字体、字号、行距等",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "length",
        "target_fields": {"full_text": True},
        "error_message": "文档内容过短，可能解析不完整",
        "fix_suggestion": "请确保文档完整上传，内容应包含完整的专利申请信息",
    },
    # 1.3 权利要求格式检查
    {
        "rule_name": "权利要求格式检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 98,
        "is_active": True,
        "description": "检查权利要求书格式是否符合规范，包括独立权利要求和从属权利要求",
        "legal_basis": "专利法第26条第4款",
        "severity": "error",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "权利要求格式不符合规范",
        "fix_suggestion": "独立权利要求应记载解决技术问题的必要技术特征；从属权利要求应引用在前的权利要求并进一步限定",
    },
    # 1.4 说明书章节完整性检查
    {
        "rule_name": "说明书章节完整性检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 90,
        "is_active": True,
        "description": "检查说明书是否包含必要章节：技术领域、背景技术、发明内容、附图说明、具体实施方式",
        "legal_basis": "专利审查指南第一部分第二章",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"description": True},
        "error_message": "说明书缺少[{section}]部分",
        "fix_suggestion": "说明书应当包含：技术领域、背景技术、发明内容、附图说明、具体实施方式等完整章节",
    },
    # 1.5 附图必要性检查
    {
        "rule_name": "附图必要性检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 92,
        "is_active": True,
        "description": "实用新型专利申请必须有说明书附图",
        "legal_basis": "专利法实施细则第17条",
        "severity": "error",
        "check_pattern": "keyword",
        "target_fields": {"drawings": True},
        "error_message": "实用新型专利申请必须有说明书附图",
        "fix_suggestion": "请提供清楚表达技术方案的附图，附图应当体现产品形状、构造或其结合的技术特征",
    },
    # 1.6 摘要质量检查
    {
        "rule_name": "摘要质量检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 85,
        "is_active": True,
        "description": "检查摘要是否在50-300字范围内，并充分说明发明技术方案",
        "legal_basis": "专利法实施细则第23条",
        "severity": "warning",
        "check_pattern": "length",
        "target_fields": {"abstract": True},
        "error_message": "摘要{reason}",
        "fix_suggestion": "摘要应当：1）文字简洁，不超过300字；2）清楚说明技术领域、技术问题、技术方案要点和主要用途；3）不得含有商业性宣传用语",
    },
    # 1.7 权利要求编号检查
    {
        "rule_name": "权利要求编号检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 88,
        "is_active": True,
        "description": "检查权利要求编号是否连续，规范",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "权利要求编号不连续: {detail}",
        "fix_suggestion": "权利要求应当用阿拉伯数字顺序编号，如1、2、3...，不得出现跳跃或重复",
    },
    # 1.8 申请文件名称检查
    {
        "rule_name": "申请文件名称检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 80,
        "is_active": True,
        "description": "检查发明名称是否符合规范",
        "legal_basis": "专利法实施细则第16条",
        "severity": "warning",
        "check_pattern": "length",
        "target_fields": {"title": True},
        "error_message": "发明名称不符合规范",
        "fix_suggestion": "发明名称应当：1）简短，一般不超过25个字；2）清楚、简要地反映要求保护的主题和类型；3）不得使用商业性宣传用语",
    },
    # 1.9 申请人信息检查
    {
        "rule_name": "申请人信息检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 82,
        "is_active": True,
        "description": "检查申请人信息是否完整、准确",
        "legal_basis": "专利法第26条",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"applicant": True},
        "error_message": "申请人信息不完整",
        "fix_suggestion": "申请人信息应当包括：姓名或名称、地址、邮政编码。委托专利代理机构的，还应当包括代理机构信息",
    },
    # 1.10 发明人信息检查
    {
        "rule_name": "发明人信息检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 83,
        "is_active": True,
        "description": "检查发明人信息是否符合规范",
        "legal_basis": "专利法第17条",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"inventor": True},
        "error_message": "发明人信息不符合规范",
        "fix_suggestion": "发明人应当是真实参与发明创造的自然人，应当使用真实姓名。发明人可以请求不公开其姓名",
    },
    # 1.11 代理人委托检查
    {
        "rule_name": "代理人委托检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 75,
        "is_active": True,
        "description": "检查专利代理委托手续是否合规",
        "legal_basis": "专利法第19条",
        "severity": "info",
        "check_pattern": "structural",
        "target_fields": {"agent": True},
        "error_message": "专利代理委托信息不完整",
        "fix_suggestion": "委托专利代理机构办理专利申请的，应当提交委托书和专利代理机构执业许可证复印件",
    },
    # 1.12 IPC分类 号检查
    {
        "rule_name": "IPC分类 号检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 78,
        "is_active": True,
        "description": "检查国际专利分类(IPC)是否正确",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"ipc_classification": True},
        "error_message": "IPC分类 号格式不正确",
        "fix_suggestion": "IPC分类 号应当符合国际专利分类表格式，如H01L21/00",
    },
    # 1.13 说明书字数检查
    {
        "rule_name": "说明书字数检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 76,
        "is_active": True,
        "description": "检查说明书字数是否符合要求",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "length",
        "target_fields": {"description": True},
        "error_message": "说明书字数不足",
        "fix_suggestion": "说明书应当对发明作出清楚、完整的说明，以所属技术领域的技术人员能够实现为准",
    },
    # 1.14 权利要求字数检查
    {
        "rule_name": "权利要求字数检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 77,
        "is_active": True,
        "description": "检查权利要求字数是否合理",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "length",
        "target_fields": {"claims": True},
        "error_message": "权利要求字数异常",
        "fix_suggestion": "权利要求应当简要、清楚、独立。独立权利要求的字数一般不宜过多",
    },
    # 1.15 附图数量检查
    {
        "rule_name": "附图数量检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 79,
        "is_active": True,
        "description": "检查附图数量是否符合要求",
        "legal_basis": "专利法实施细则第17条",
        "severity": "info",
        "check_pattern": "length",
        "target_fields": {"drawings": True},
        "error_message": "附图数量不符合要求",
        "fix_suggestion": "实用新型专利申请应当有附图，说明书附图应当清楚显示发明技术方案的技术特征",
    },
    # 1.16 说明书摘要字数检查
    {
        "rule_name": "说明书摘要字数检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 84,
        "is_active": True,
        "description": "检查摘要字数是否符合规范",
        "legal_basis": "专利法实施细则第23条",
        "severity": "warning",
        "check_pattern": "length",
        "target_fields": {"abstract": True},
        "error_message": "摘要字数不符合规范（应50-300字）",
        "fix_suggestion": "摘要字数应当在50-300字之间，简明扼要说明发明技术方案",
    },
    # 1.17 申请日确认检查
    {
        "rule_name": "申请日确认检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 81,
        "is_active": True,
        "description": "检查申请日信息是否完整",
        "legal_basis": "专利法第28条",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"application_date": True},
        "error_message": "申请日信息缺失或不完整",
        "fix_suggestion": "申请日是专利局收到专利申请文件的日期，申请日信息应当准确",
    },
    # 1.18 优先权声明检查
    {
        "rule_name": "优先权声明检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 70,
        "is_active": True,
        "description": "检查优先权声明是否符合要求",
        "legal_basis": "专利法第29条",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"full_text": True},
        "error_message": "优先权声明信息不完整",
        "fix_suggestion": "要求优先权的，应当在申请时提出书面声明，并在三个月内提交在先申请文件副本",
    },
    # 1.19 保密审查请求检查
    {
        "rule_name": "保密审查请求检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 65,
        "is_active": True,
        "description": "检查保密审查请求是否符合要求",
        "legal_basis": "专利法第4条",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"full_text": True},
        "error_message": "涉及国防利益的专利申请需保密审查",
        "fix_suggestion": "涉及国家安全或者重大利益需要保密的专利申请，应当提出保密审查请求",
    },
    # 1.20 文件签署检查
    {
        "rule_name": "文件签署检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 73,
        "is_active": True,
        "description": "检查申请文件是否已签署",
        "legal_basis": "专利审查指南",
        "severity": "error",
        "check_pattern": "keyword",
        "target_fields": {"full_text": True},
        "error_message": "申请文件缺少必要签署",
        "fix_suggestion": "申请文件应当有申请人、发明人或者代理机构的签字或盖章",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # 二级规则 - 实质审查规则 (25条)
    # ═══════════════════════════════════════════════════════════════════════
    
    # 2.1 保护客体审查
    {
        "rule_name": "保护客体审查",
        "rule_type": "subject_matter",
        "rule_category": "level2",
        "priority": 75,
        "is_active": True,
        "description": "判断申请是否属于实用新型保护的客体",
        "legal_basis": "专利法第2条第3款",
        "severity": "error",
        "check_pattern": "keyword",
        "target_fields": {"full_text": True},
        "error_message": "技术方案可能涉及{matter}，不属于实用新型保护客体",
        "fix_suggestion": "实用新型只保护产品形状、构造或其结合的技术方案。不保护：1）方法；2）材料配方；3）物品用途；4）计算机程序；5）智力活动规则",
    },
    # 2.2 权利要求清楚性检查
    {
        "rule_name": "权利要求清楚性检查",
        "rule_type": "clarity",
        "rule_category": "level2",
        "priority": 70,
        "is_active": True,
        "description": "检查权利要求是否存在表述不清楚的问题",
        "legal_basis": "专利法第26条第4款",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"claims": True},
        "error_message": "权利要求含有模糊用语：{term}",
        "fix_suggestion": "建议将模糊用语（如'大约'、'约'、'较大'、'适当'、'合适'、'优选地'）替换为明确的技术参数或数值范围",
    },
    # 2.3 权利要求说明书支持性检查
    {
        "rule_name": "权利要求说明书支持性检查",
        "rule_type": "support",
        "rule_category": "level2",
        "priority": 68,
        "is_active": True,
        "description": "检查权利要求的技术方案是否得到说明书支持",
        "legal_basis": "专利法第26条第4款",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"claims": True, "description": True},
        "error_message": "权利要求{num}中的术语{missing}在说明书中未找到明确记载",
        "fix_suggestion": "说明书中应当充分公开权利要求的技术方案，使所属技术领域的技术人员能够实现。应当用具体的技术特征来限定权利要求",
    },
    # 2.4 说明书充分公开检查
    {
        "rule_name": "说明书充分公开检查",
        "rule_type": "sufficiency",
        "rule_category": "level2",
        "priority": 65,
        "is_active": True,
        "description": "检查说明书是否充分公开了发明",
        "legal_basis": "专利法第26条第3款",
        "severity": "warning",
        "check_pattern": "length",
        "target_fields": {"description": True},
        "error_message": "具体实施方式部分内容过短（{length}字），可能公开不充分",
        "fix_suggestion": "具体实施方式应当：1）详细说明至少一个具体实施例；2）清楚说明发明的技术方案；3）提供足够的技术细节使技术人员能够实现",
    },
    # 2.5 单一性检查
    {
        "rule_name": "单一性检查",
        "rule_type": "unity",
        "rule_category": "level2",
        "priority": 60,
        "is_active": True,
        "description": "检查是否存在单一性问题",
        "legal_basis": "专利法第31条第1款",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "包含{count}项独立权利要求，可能不满足单一性要求",
        "fix_suggestion": "一件专利申请应当限于一项发明。属于同一发明构思的两项以上的发明或者实用新型，可以作为一件申请提出。建议将属于同一发明构思的技术方案作为一组专利申请",
    },
    # 2.6 权利要求依赖关系检查
    {
        "rule_name": "权利要求依赖关系检查",
        "rule_type": "dependency",
        "rule_category": "level2",
        "priority": 72,
        "is_active": True,
        "description": "检查从属权利要求是否正确引用在先权利要求",
        "legal_basis": "专利审查指南",
        "severity": "error",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "从属权利要求{num}未明确引用其他权利要求",
        "fix_suggestion": "从属权利要求应当用附加的技术特征对引用的权利要求作进一步限定，并应当用'根据权利要求X所述...'的方式引用在前的权利要求",
    },
    # 2.7 附图质量检查
    {
        "rule_name": "附图质量检查",
        "rule_type": "drawings",
        "rule_category": "level2",
        "priority": 62,
        "is_active": True,
        "description": "检查附图质量是否符合规范",
        "legal_basis": "专利法实施细则第17条",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"drawings": True},
        "error_message": "附图质量不符合规范",
        "fix_suggestion": "附图应当：1）使用黑色绘制；2）线条清晰；3）附图不得着色；4）应当用阿拉伯数字编号；5）应当清楚显示技术特征",
    },
    # 2.8 序列表检查
    {
        "rule_name": "序列表检查",
        "rule_type": "sequence",
        "rule_category": "level2",
        "priority": 50,
        "is_active": True,
        "description": "涉及生物序列的专利申请需要检查序列表",
        "legal_basis": "专利法实施细则第34条",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"full_text": True},
        "error_message": "涉及生物序列（{type}），请确认是否需要提交序列表",
        "fix_suggestion": "涉及基因、蛋白、氨基酸，核苷酸等生物序列时，需要提交符合规定的序列表。序列表应当使用规定的格式",
    },
    # 2.9 技术效果充分性检查
    {
        "rule_name": "技术效果充分性检查",
        "rule_type": "effect",
        "rule_category": "level2",
        "priority": 58,
        "is_active": True,
        "description": "检查说明书是否充分描述了技术效果",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "说明书未充分描述技术效果",
        "fix_suggestion": "说明书应当说明发明的有益效果，最好有实验数据或对比文件支持。有益效果可以通过结构特点、作用机理或实验数据来说明",
    },
    # 2.10 背景技术引用检查
    {
        "rule_name": "背景技术引用检查",
        "rule_type": "background",
        "rule_category": "level2",
        "priority": 55,
        "is_active": True,
        "description": "检查背景技术部分是否合理引用现有技术",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "length",
        "target_fields": {"description": True},
        "error_message": "背景技术部分内容过少",
        "fix_suggestion": "背景技术应当说明该发明所属技术领域的现有技术状况，客观指出背景技术中存在的问题和不足，为发明提供技术背景支持",
    },
    # 2.11 独立权利要求必要特征检查
    {
        "rule_name": "独立权利要求必要特征检查",
        "rule_type": "essential",
        "rule_category": "level2",
        "priority": 63,
        "is_active": True,
        "description": "检查独立权利要求是否记载了解决技术问题的必要技术特征",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"claims": True},
        "error_message": "独立权利要求可能缺少必要技术特征",
        "fix_suggestion": "独立权利要求应当记载解决发明技术问题所必须的全部技术特征，使其保护范围适当且能够获得说明书支持",
    },
    # 2.12 说明书清楚性检查
    {
        "rule_name": "说明书清楚性检查",
        "rule_type": "clarity",
        "rule_category": "level2",
        "priority": 56,
        "is_active": True,
        "description": "检查说明书表述是否清楚",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "说明书可能存在表述不清楚的问题",
        "fix_suggestion": "说明书应当用词准确、语句清楚，使所属技术领域的技术人员能够准确理解发明技术方案，不得含有含糊不清的表述",
    },
    # 2.13 权利要求书实质内容检查
    {
        "rule_name": "权利要求书实质内容检查",
        "rule_type": "substance",
        "rule_category": "level2",
        "priority": 57,
        "is_active": True,
        "description": "检查权利要求书是否记载了实质性的技术解决方案",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "length",
        "target_fields": {"claims": True},
        "error_message": "权利要求书内容过于简单",
        "fix_suggestion": "权利要求书应当记载发明的技术解决方案，明确请求保护的技术方案类型和范围。权利要求应当以说明书为依据",
    },
    # 2.14 具体实施方式完整性检查
    {
        "rule_name": "具体实施方式完整性检查",
        "rule_type": "embodiment",
        "rule_category": "level2",
        "priority": 59,
        "is_active": True,
        "description": "检查具体实施方式是否完整",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "length",
        "target_fields": {"description": True},
        "error_message": "具体实施方式不完整",
        "fix_suggestion": "具体实施方式应当：1）详细描述一个或多个优选实施例；2）说明实施方式的具体结构、连接关系和动作过程；3）给出实现发明技术方案的具体技术途径",
    },
    # 2.15 附图说明与实施方式对应性检查
    {
        "rule_name": "附图说明与实施方式对应性检查",
        "rule_type": "correspondence",
        "rule_category": "level2",
        "priority": 52,
        "is_active": True,
        "description": "检查附图说明与具体实施方式是否对应",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True, "drawings": True},
        "error_message": "附图说明与实施方式可能不对应",
        "fix_suggestion": "附图说明应当对各幅附图作简要说明，具体实施方式应当结合附图进行说明，使技术人员能够理解发明",
    },
    # 2.16 发明构思一致性检查
    {
        "rule_name": "发明构思一致性检查",
        "rule_type": "consistency",
        "rule_category": "level2",
        "priority": 54,
        "is_active": True,
        "description": "检查权利要求与说明书发明内容是否一致",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"claims": True, "description": True},
        "error_message": "权利要求与说明书发明内容可能不一致",
        "fix_suggestion": "权利要求保护的技术方案应当在说明书发明内容中有明确记载，两者应当保持一致",
    },
    # 2.17 技术问题明确性检查
    {
        "rule_name": "技术问题明确性检查",
        "rule_type": "problem",
        "rule_category": "level2",
        "priority": 51,
        "is_active": True,
        "description": "检查说明书中技术问题是否明确",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "技术问题不明确",
        "fix_suggestion": "说明书应当清楚、客观地反映发明的技术问题，该问题应当可以通过发明的技术方案来解决",
    },
    # 2.18 实施例充分性检查
    {
        "rule_name": "实施例充分性检查",
        "rule_type": "example",
        "rule_category": "level2",
        "priority": 53,
        "is_active": True,
        "description": "检查实施例是否充分",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "length",
        "target_fields": {"description": True},
        "error_message": "实施例内容不够充分",
        "fix_suggestion": "应当提供足够数量的实施例，使技术人员能够充分理解发明并再现发明技术方案",
    },
    # 2.19 数值范围合理性检查
    {
        "rule_name": "数值范围合理性检查",
        "rule_type": "range",
        "rule_category": "level2",
        "priority": 48,
        "is_active": True,
        "description": "检查权利要求中的数值范围是否合理",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"claims": True},
        "error_message": "数值范围可能过宽",
        "fix_suggestion": "权利要求中的数值范围应当得到说明书支持，且范围应当合理",
    },
    # 2.20 附图标记一致性检查
    {
        "rule_name": "附图标记一致性检查",
        "rule_type": "marking",
        "rule_category": "level2",
        "priority": 46,
        "is_active": True,
        "description": "检查说明书中附图标记与附图是否一致",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True, "drawings": True},
        "error_message": "附图标记与附图可能不一致",
        "fix_suggestion": "说明书中提到的附图标记应当与附图中的标记一致",
    },
    # 2.21 英文缩写首次定义检查
    {
        "rule_name": "英文缩写首次定义检查",
        "rule_type": "abbreviation",
        "rule_category": "level2",
        "priority": 44,
        "is_active": True,
        "description": "检查英文缩写是否在首次出现时给出定义",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "英文缩写可能未在首次出现时定义",
        "fix_suggestion": "说明书首次使用英文缩写时应当给出中文定义或全称",
    },
    # 2.22 前后描述一致性检查
    {
        "rule_name": "前后描述一致性检查",
        "rule_type": "consistency",
        "rule_category": "level2",
        "priority": 47,
        "is_active": True,
        "description": "检查说明书前后描述是否一致",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "说明书前后描述可能不一致",
        "fix_suggestion": "说明书各部分描述应当保持一致，避免出现矛盾或歧义",
    },
    # 2.23 权利要求保护范围合理性检查
    {
        "rule_name": "权利要求保护范围合理性检查",
        "rule_type": "scope",
        "rule_category": "level2",
        "priority": 61,
        "is_active": True,
        "description": "检查权利要求保护范围是否合理",
        "legal_basis": "专利法第26条",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"claims": True},
        "error_message": "权利要求保护范围可能过宽",
        "fix_suggestion": "权利要求的保护范围应当与说明书公开的范围相适应，不能超出说明书公开的范围",
    },
    # 2.24 技术手段新颖性暗示检查
    {
        "rule_name": "技术手段新颖性暗示检查",
        "rule_type": "novelty",
        "rule_category": "level2",
        "priority": 43,
        "is_active": True,
        "description": "检查发明是否暗示了技术手段的新颖性",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "技术手段新颖性描述不足",
        "fix_suggestion": "说明书应当客观描述发明的技术方案，不需要声称新颖性或创造性",
    },
    # 2.25 商业宣传用语检查
    {
        "rule_name": "商业宣传用语检查",
        "rule_type": "commerce",
        "rule_category": "level2",
        "priority": 45,
        "is_active": True,
        "description": "检查申请文件中是否含有商业性宣传用语",
        "legal_basis": "专利法第5条",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"full_text": True},
        "error_message": "申请文件含有商业性宣传用语",
        "fix_suggestion": "专利申请文件不得含有商业性宣传用语，如'最先进的'、'第一'等",
    },
    # ═══════════════════════════════════════════════════════════════════════
    # 二级规则 - 实质审查补充规则 (30条)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "rule_name": "技术方案完整性检查",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 88,
        "is_active": True,
        "description": "检查技术方案是否完整记载了解决技术问题的必要技术特征",
        "legal_basis": "专利法第26条第4款",
        "severity": "error",
        "check_pattern": "structural",
        "target_fields": {"claims": True, "description": True},
        "error_message": "技术方案不完整",
        "fix_suggestion": "请确保权利要求书记载了解决技术问题的全部必要技术特征",
    },
    {
        "rule_name": "说明书充分描述检查",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 87,
        "is_active": True,
        "description": "检查说明书是否充分描述了发明的技术方案",
        "legal_basis": "专利法第26条第3款",
        "severity": "error",
        "check_pattern": "structural",
        "target_fields": {"description": True},
        "error_message": "说明书公开不充分",
        "fix_suggestion": "说明书应当对发明作出清楚、完整的说明，以所属技术领域的技术人员能够实现为准",
    },
    {
        "rule_name": "权利要求保护范围合理性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 86,
        "is_active": True,
        "description": "检查权利要求的保护范围是否合理",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "保护范围不合理",
        "fix_suggestion": "权利要求的保护范围应当与说明书公开的内容相适应",
    },
    {
        "rule_name": "技术问题明确性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 85,
        "is_active": True,
        "description": "检查发明解决的技术问题是否明确",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "技术问题不明确",
        "fix_suggestion": "说明书应当明确记载发明要解决的技术问题",
    },
    {
        "rule_name": "技术效果可验证性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 84,
        "is_active": True,
        "description": "检查技术效果是否可以通过实验验证",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "技术效果描述不足以验证",
        "fix_suggestion": "应当提供实验数据或证据证明技术效果",
    },
    {
        "rule_name": "实施例充分性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 83,
        "is_active": True,
        "description": "检查具体实施方式是否充分",
        "legal_basis": "专利法第26条第3款",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"description": True},
        "error_message": "实施例不充分",
        "fix_suggestion": "应当提供足够数量的实施例使技术人员能够实现发明",
    },
    {
        "rule_name": "数值范围合理性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 82,
        "is_active": True,
        "description": "检查权利要求中的数值范围是否合理",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"claims": True, "description": True},
        "error_message": "数值范围不合理",
        "fix_suggestion": "数值范围应当得到说明书的支持",
    },
    {
        "rule_name": "附图标记一致性",
        "rule_type": "formal",
        "rule_category": "level2",
        "priority": 81,
        "is_active": True,
        "description": "检查附图标记与说明书描述是否一致",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"drawings": True, "description": True},
        "error_message": "附图标记不一致",
        "fix_suggestion": "附图标记应当与说明书中的描述一致",
    },
    {
        "rule_name": "英文缩写首次定义",
        "rule_type": "formal",
        "rule_category": "level2",
        "priority": 80,
        "is_active": True,
        "description": "检查英文缩写是否在说明书中首次定义",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "英文缩写未定义",
        "fix_suggestion": "首次使用的英文缩写应当在说明书中给出定义",
    },
    {
        "rule_name": "前后描述一致性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 79,
        "is_active": True,
        "description": "检查说明书前后描述是否一致",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"description": True},
        "error_message": "前后描述不一致",
        "fix_suggestion": "说明书的发明内容、具体实施方式等部分描述应当一致",
    },
    {
        "rule_name": "技术领域正确定位",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 78,
        "is_active": True,
        "description": "检查技术领域是否正确定位",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "技术领域定位不准确",
        "fix_suggestion": "技术领域应当定位到具体的技术领域",
    },
    {
        "rule_name": "背景技术引用检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 77,
        "is_active": True,
        "description": "检查背景技术是否适当引用",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "背景技术引用不完整",
        "fix_suggestion": "应当客观指出背景技术中存在的问题",
    },
    {
        "rule_name": "发明构思一致性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 76,
        "is_active": True,
        "description": "检查发明构思是否一致",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"claims": True, "description": True},
        "error_message": "发明构思不一致",
        "fix_suggestion": "独立权利要求与说明书记载的发明构思应当一致",
    },
    {
        "rule_name": "权利要求概括合理性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 75,
        "is_active": True,
        "description": "检查权利要求的概括是否合理",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "权利要求概括过宽",
        "fix_suggestion": "权利要求应当得到说明书的支持",
    },
    {
        "rule_name": "技术特征描述准确性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 74,
        "is_active": True,
        "description": "检查技术特征描述是否准确",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"claims": True, "description": True},
        "error_message": "技术特征描述不准确",
        "fix_suggestion": "技术特征应当使用准确的技术术语描述",
    },
    {
        "rule_name": "PCT申请形式检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 73,
        "is_active": True,
        "description": "检查PCT申请是否符合形式要求",
        "legal_basis": "专利合作条约",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"full_text": True},
        "error_message": "PCT申请形式不符合要求",
        "fix_suggestion": "请确保符合PCT申请的形式要求",
    },
    {
        "rule_name": "优先权文件检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 72,
        "is_active": True,
        "description": "检查优先权声明是否有效",
        "legal_basis": "专利法第30条",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"full_text": True},
        "error_message": "优先权可能无效",
        "fix_suggestion": "优先权文件应当在期限内提交",
    },
    {
        "rule_name": "保密审查请求检查",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 71,
        "is_active": True,
        "description": "检查是否需要保密审查",
        "legal_basis": "专利法第4条",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"full_text": True},
        "error_message": "可能需要保密审查",
        "fix_suggestion": "涉及国家安全的发明创造需要保密审查",
    },
    {
        "rule_name": "生物材料保藏检查",
        "rule_type": "formal",
        "rule_category": "level2",
        "priority": 70,
        "is_active": True,
        "description": "检查涉及生物材料的申请是否已保藏",
        "legal_basis": "专利法实施细则第24条",
        "severity": "error",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "生物材料未保藏",
        "fix_suggestion": "涉及生物材料的发明专利申请，应当提交保藏单位出具的保藏证明",
    },
    {
        "rule_name": "核苷酸序列检查",
        "rule_type": "formal",
        "rule_category": "level2",
        "priority": 69,
        "is_active": True,
        "description": "检查涉及核苷酸序列的申请是否符合要求",
        "legal_basis": "专利法实施细则第34条",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "序列格式可能不符合要求",
        "fix_suggestion": "核苷酸序列应当按照规定格式提交",
    },
    {
        "rule_name": "遗传资源来源披露",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 68,
        "is_active": True,
        "description": "检查是否披露了遗传资源的合法来源",
        "legal_basis": "专利法第5条",
        "severity": "error",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "未披露遗传资源来源",
        "fix_suggestion": "利用遗传资源完成的发明创造，应当说明遗传资源的直接来源",
    },
    {
        "rule_name": "申请文件文字质量",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 67,
        "is_active": True,
        "description": "检查申请文件文字是否存在错误",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"full_text": True},
        "error_message": "申请文件存在文字错误",
        "fix_suggestion": "申请文件应当文字清晰，无错别字",
    },
    {
        "rule_name": "附图清晰度要求",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 66,
        "is_active": True,
        "description": "检查附图是否清晰可辨",
        "legal_basis": "专利法实施细则第17条",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"drawings": True},
        "error_message": "附图不够清晰",
        "fix_suggestion": "附图应当清晰可辨，线条均匀",
    },
    {
        "rule_name": "说明书摘要实用性",
        "rule_type": "formal",
        "rule_category": "level1",
        "priority": 65,
        "is_active": True,
        "description": "检查摘要是否具有实用性信息",
        "legal_basis": "专利法实施细则第23条",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"abstract": True},
        "error_message": "摘要实用性信息不足",
        "fix_suggestion": "摘要应当概括说明发明的技术方案和主要用途",
    },
    {
        "rule_name": "权利要求单一性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 64,
        "is_active": True,
        "description": "检查权利要求是否满足单一性要求",
        "legal_basis": "专利法第31条第1款",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "可能存在单一性问题",
        "fix_suggestion": "一组权利要求应当属于一个总的发明构思",
    },
    {
        "rule_name": "从属权利要求限定性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 63,
        "is_active": True,
        "description": "检查从属权利要求是否对其引用权利要求进行了进一步限定",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "从属权利要求未进行有效限定",
        "fix_suggestion": "从属权利要求应当对其引用的权利要求的技术特征进行进一步限定",
    },
    {
        "rule_name": "独立权利要求必要特征",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 62,
        "is_active": True,
        "description": "检查独立权利要求是否记载了必要技术特征",
        "legal_basis": "专利法第26条第4款",
        "severity": "error",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "独立权利要求缺少必要技术特征",
        "fix_suggestion": "独立权利要求应当记载解决技术问题的必要技术特征",
    },
    {
        "rule_name": "技术方案新颖性暗示",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 61,
        "is_active": True,
        "description": "检查技术方案是否暗示了新颖性特征",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "新颖性特征描述不足",
        "fix_suggestion": "应当在说明书中描述与现有技术的区别特征",
    },
    {
        "rule_name": "附图与实施方式对应",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 60,
        "is_active": True,
        "description": "检查附图与具体实施方式是否对应",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"drawings": True, "description": True},
        "error_message": "附图与实施方式不对应",
        "fix_suggestion": "具体实施方式应当有对应的附图说明",
    },
    {
        "rule_name": "技术方案可实现性",
        "rule_type": "substantive",
        "rule_category": "level2",
        "priority": 59,
        "is_active": True,
        "description": "检查技术方案是否能够实现",
        "legal_basis": "专利法第26条第3款",
        "severity": "error",
        "check_pattern": "structural",
        "target_fields": {"description": True},
        "error_message": "技术方案无法实现",
        "fix_suggestion": "说明书应当充分公开，使技术人员能够实现",
    },
    # ═══════════════════════════════════════════════════════════════════════
    # 三级规则 - 高级审查规则 (30条)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "rule_name": "权利要求多主题检查",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 58,
        "is_active": True,
        "description": "检查权利要求是否涉及多个发明主题",
        "legal_basis": "专利法第31条",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "权利要求涉及多个发明主题",
        "fix_suggestion": "一件专利申请应当限于一项发明，或者属于一个总的发明构思的多项发明",
    },
    {
        "rule_name": "技术方案可行性验证",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 57,
        "is_active": True,
        "description": "检查技术方案是否能够解决技术问题",
        "legal_basis": "专利法第26条第3款",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"description": True},
        "error_message": "技术方案可能无法解决技术问题",
        "fix_suggestion": "说明书应当清楚说明技术方案如何解决技术问题",
    },
    {
        "rule_name": "技术手段合理性检查",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 56,
        "is_active": True,
        "description": "检查技术手段是否合理",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "技术手段描述可能不合理",
        "fix_suggestion": "技术手段应当符合技术逻辑，能够实现发明目的",
    },
    {
        "rule_name": "发明目的明确性检查",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 55,
        "is_active": True,
        "description": "检查发明目的是否明确",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "发明目的不明确",
        "fix_suggestion": "说明书应当明确记载发明要解决的技术问题",
    },
    {
        "rule_name": "技术效果可重复性检查",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 54,
        "is_active": True,
        "description": "检查技术效果是否可以重复实现",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "技术效果可能无法重复",
        "fix_suggestion": "说明书应当提供足够的技术细节使技术人员能够重复实现技术效果",
    },
    {
        "rule_name": "实施方式可替代性检查",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 53,
        "is_active": True,
        "description": "检查实施方式是否有可替代方案",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "实施方式可能缺少替代方案",
        "fix_suggestion": "说明书应当提供多个实施方式或说明其可替代性",
    },
    {
        "rule_name": "权利要求保护范围适度性",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 52,
        "is_active": True,
        "description": "检查权利要求保护范围是否适度",
        "legal_basis": "专利法第26条",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "保护范围可能不适度",
        "fix_suggestion": "权利要求的保护范围应当适度，既要确保获得保护又要能够实现",
    },
    {
        "rule_name": "技术特征组合合理性",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 51,
        "is_active": True,
        "description": "检查技术特征组合是否合理",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "技术特征组合可能不合理",
        "fix_suggestion": "技术特征应当按照技术逻辑进行组合",
    },
    {
        "rule_name": "说明书技术细节充分性",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 50,
        "is_active": True,
        "description": "检查说明书技术细节是否充分",
        "legal_basis": "专利法第26条第3款",
        "severity": "warning",
        "check_pattern": "length",
        "target_fields": {"description": True},
        "error_message": "技术细节不够充分",
        "fix_suggestion": "说明书应当提供充分的技术细节，使技术人员能够实现发明",
    },
    {
        "rule_name": "附图布局合理性检查",
        "rule_type": "formal",
        "rule_category": "level3",
        "priority": 49,
        "is_active": True,
        "description": "检查附图布局是否合理",
        "legal_basis": "专利法实施细则第17条",
        "severity": "info",
        "check_pattern": "structural",
        "target_fields": {"drawings": True},
        "error_message": "附图布局不合理",
        "fix_suggestion": "附图应当布局合理，清楚显示技术特征",
    },
    {
        "rule_name": "权利要求引用准确性",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 48,
        "is_active": True,
        "description": "检查权利要求引用是否准确",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"claims": True},
        "error_message": "权利要求引用不准确",
        "fix_suggestion": "从属权利要求应当准确引用其引用的权利要求",
    },
    {
        "rule_name": "技术术语一致性",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 47,
        "is_active": True,
        "description": "检查技术术语使用是否一致",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True, "claims": True},
        "error_message": "技术术语使用不一致",
        "fix_suggestion": "说明书中技术术语应当保持一致",
    },
    {
        "rule_name": "数值单位准确性",
        "rule_type": "formal",
        "rule_category": "level3",
        "priority": 46,
        "is_active": True,
        "description": "检查数值单位是否准确",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"claims": True, "description": True},
        "error_message": "数值单位可能不准确",
        "fix_suggestion": "数值单位应当使用法定计量单位",
    },
    {
        "rule_name": "化学式格式规范性",
        "rule_type": "formal",
        "rule_category": "level3",
        "priority": 45,
        "is_active": True,
        "description": "检查化学式格式是否规范",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "化学式格式可能不规范",
        "fix_suggestion": "化学式应当按照规范格式书写",
    },
    {
        "rule_name": "数学公式表达准确性",
        "rule_type": "formal",
        "rule_category": "level3",
        "priority": 44,
        "is_active": True,
        "description": "检查数学公式表达是否准确",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "数学公式表达可能不准确",
        "fix_suggestion": "数学公式应当准确表达技术方案",
    },
    {
        "rule_name": "流程图清晰度检查",
        "rule_type": "formal",
        "rule_category": "level3",
        "priority": 43,
        "is_active": True,
        "description": "检查流程图是否清晰",
        "legal_basis": "专利法实施细则第17条",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"drawings": True},
        "error_message": "流程图不够清晰",
        "fix_suggestion": "流程图应当清晰表达技术步骤",
    },
    {
        "rule_name": "表格数据完整性",
        "rule_type": "formal",
        "rule_category": "level3",
        "priority": 42,
        "is_active": True,
        "description": "检查表格数据是否完整",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "structural",
        "target_fields": {"description": True},
        "error_message": "表格数据不完整",
        "fix_suggestion": "表格应当包含完整的数据和表头",
    },
    {
        "rule_name": "实施例数据可靠性",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 41,
        "is_active": True,
        "description": "检查实施例数据是否可靠",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "实施例数据可能不可靠",
        "fix_suggestion": "实施例数据应当来源于可信的实验或计算",
    },
    {
        "rule_name": "对比实验规范性",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 40,
        "is_active": True,
        "description": "检查对比实验是否规范",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "对比实验可能不规范",
        "fix_suggestion": "对比实验应当包含对比例和发明例",
    },
    {
        "rule_name": "参数范围合理性验证",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 39,
        "is_active": True,
        "description": "检查参数范围是否合理",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"claims": True, "description": True},
        "error_message": "参数范围可能不合理",
        "fix_suggestion": "参数范围应当得到说明书支持且合理",
    },
    {
        "rule_name": "技术方案可实施性验证",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 38,
        "is_active": True,
        "description": "检查技术方案是否可实施",
        "legal_basis": "专利法第26条第3款",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"description": True},
        "error_message": "技术方案可能无法实施",
        "fix_suggestion": "说明书应当充分公开使技术人员能够实施",
    },
    {
        "rule_name": "发明技术效果显著性",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 37,
        "is_active": True,
        "description": "检查发明技术效果是否显著",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "技术效果显著性描述不足",
        "fix_suggestion": "应当说明发明相对于现有技术的有益效果",
    },
    {
        "rule_name": "技术问题解决方案匹配度",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 36,
        "is_active": True,
        "description": "检查技术问题与解决方案是否匹配",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "keyword",
        "target_fields": {"description": True},
        "error_message": "技术问题与解决方案不匹配",
        "fix_suggestion": "技术解决方案应当能够解决说明的技术问题",
    },
    {
        "rule_name": "权利要求新颖性暗示",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 35,
        "is_active": True,
        "description": "检查权利要求是否暗示新颖性",
        "legal_basis": "专利审查指南",
        "severity": "info",
        "check_pattern": "keyword",
        "target_fields": {"claims": True},
        "error_message": "新颖性特征不够明确",
        "fix_suggestion": "权利要求应当明确记载与现有技术的区别特征",
    },
    {
        "rule_name": "技术手段完整性",
        "rule_type": "substantive",
        "rule_category": "level3",
        "priority": 34,
        "is_active": True,
        "description": "检查技术手段是否完整",
        "legal_basis": "专利审查指南",
        "severity": "warning",
        "check_pattern": "structural",
        "target_fields": {"description": True},
        "error_message": "技术手段不完整",
        "fix_suggestion": "说明书应当完整记载实现发明所需的技术手段",
    },
]


async def init_patent_rules(db):
    """初始化预置专利审查规则"""
    from sqlalchemy import select, func
    
    # 获取已存在的规则名称
    result = await db.execute(
        select(ExaminationRule.rule_name).where(ExaminationRule.rule_name.isnot(None))
    )
    existing_rule_names = set(result.scalars().all())
    
    # 添加缺失的规则
    new_rules = []
    for rule_data in DEFAULT_PATENT_RULES:
        if rule_data["rule_name"] not in existing_rule_names:
            rule = ExaminationRule(**rule_data)
            new_rules.append(rule)
    
    if new_rules:
        db.add_all(new_rules)
        await db.commit()
    
    # 清理可能存在的重复规则，只保留每个rule_name的第一条
    from sqlalchemy import delete
    subquery = (
        select(func.min(ExaminationRule.id))
        .group_by(ExaminationRule.rule_name)
        .scalar_subquery()
    )
    await db.execute(
        delete(ExaminationRule).where(ExaminationRule.id.notin_(subquery))
    )
    await db.commit()
    
    # 统计最终结果
    final_count = await db.execute(select(func.count(ExaminationRule.id)))
    total_count = final_count.scalar() or 0
    
    level1_count = sum(1 for r in DEFAULT_PATENT_RULES if r["rule_category"] == "level1")
    level2_count = sum(1 for r in DEFAULT_PATENT_RULES if r["rule_category"] == "level2")
    
    if new_rules:
        print(f"[规则初始化] 已添加 {len(new_rules)} 条新规则，现有 {total_count} 条规则（一级规则{level1_count}条，二级规则{level2_count}条）")
    else:
        print(f"[规则初始化] 规则已存在，现有 {total_count} 条规则（一级规则{level1_count}条，二级规则{level2_count}条）")


async def reset_patent_rules(db):
    """重置专利审查规则（删除并重新创建）"""
    from sqlalchemy import delete
    
    # 删除所有现有规则
    await db.execute(delete(ExaminationRule))
    await db.commit()
    
    # 添加预置规则
    for rule_data in DEFAULT_PATENT_RULES:
        rule = ExaminationRule(**rule_data)
        db.add(rule)
    
    await db.commit()
    level1_count = sum(1 for r in DEFAULT_PATENT_RULES if r["rule_category"] == "level1")
    level2_count = sum(1 for r in DEFAULT_PATENT_RULES if r["rule_category"] == "level2")
    print(f"[规则重置] 已重新创建 {len(DEFAULT_PATENT_RULES)} 条预置专利审查规则（一级规则{level1_count}条，二级规则{level2_count}条）")
