-- 初始化数据库权限
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO patent_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO patent_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO patent_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO patent_user;
